import UIKit

struct StringConstants {
    static let kMsgSuhaniSStop: String = "Suhani’s Stop, Kukatpally"
    static let k: String = ""
    static let kLblVegan: String = "Vegan"
    static let kLblRescued: String = "Rescued"
    static let kLblDailyValue: String = "*Daily value"
    static let kLblSodium: String = "Sodium"
    static let kLbl1: String = "1"
    static let kLbl22: String = "2"
    static let kLbl5: String = "5%*"
    static let kLbl2: String = "+"
    static let kLbl125: String = "₹125"
    static let kLblDescription: String = "Description"
    static let kLbl145Cal: String = "145 cal"
    static let kLblPotassium: String = "Potassium"
    static let kLbl25g: String = "2.5g"
    static let kLblAppNavigation: String = "App Navigation"
    static let kMsgOurFriedRice: String = "Our fried rice is made from the finest ingredients and veggies. single dish is made with fresh vegetables, rescued."
    static let kHttpFail: String = "HTTP request failed"
    static let kLblEdit: String = "Edit"
    static let kLblJalapeno: String = "Jalapeno"
    static let kLblProtein: String = "Protein"
    static let kLblSelectUser: String = "Select User  -"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLbl34: String = "34"
    static let kMsgCheckYourApp: String = "Check your app's UI from the below demo screens of your app."
    static let kLbl33: String = "33"
    static let kLbl30Min: String = "30 min"
    static let kLbl16: String = "16"
    static let kLblUser1: String = "User 1"
    static let kMsgNutritionalVal: String = "Nutritional Value"
    static let kLblUser2: String = "User 2"
    static let kLbl19: String = "19%*"
    static let kLblJollofRice: String = "Jollof Rice"
    static let kLblAdditions: String = "Additions"
    static let kLbl: String = "-  "
    static let kLblCarbohydrates: String = "Carbohydrates"
    static let kLbl192: String = "19"
    static let kLbl147g: String = "14.7g"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLbl250: String = "₹250"
    static let kMsgRichInVitamin: String = "Rich in Vitamin A, C and B3"
    static let kLblIngredients: String = "Ingredients"
}
